---
title: "Impact of the 2016 Presidential Election on Urban Mobility: Who is Affected the Most?"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
# library(tidyverse)
# library(sf)
# 
# travel_times <- read_csv(file = "data/boston-censustracts-2019-3-All-HourlyAggregate.csv")
# shapes <- st_read(dsn = "data/boston_censustracts.json")
```

Data is taken from [here](https://movement.uber.com/?lang=en-US) from the "Travel Times" dataset for Boston. We want to look at how different transit policies impact the travel times within a city.

This research will first look at how travel times across Washington D.C. generally vary before and during the 2016 presidential election. We will then explore variations of this across different neighborhoods, income, and racial divides to examine bottlenecks in mobility for different identity groups. This research will contribute in explaining and interpreting variations in urban mobility during major events. It adds to the limited literature covering congestion capacity during agglomerating events such as the Olympics, natural disasters, and major holidays. It also aims to contribute by identifying heterogeneity across different socioeconomic barriers to better inform urban policy and planning aiming for equitable mobility.

## Introduction

* Explain traffic/congestion/mobility with statistics etc.
* Explain how these factors are magnified during a major event like the Olympics
* Tie in how different people may be affected (?)
* Start introducing the 2016 Election

